services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql_pedidos
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: pedidos_db
      MYSQL_USER: desarrollador
      MYSQL_PASSWORD: desarrollador123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: